[package]
name = "ipmog"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.29", features = ["crossterm"] }
crossterm = "0.28"
ureq = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
color-eyre = "0.6"
